### PR TITLE
Drop email support

### PR DESCRIPTION
**Pull request by fromonesrc**
This isn't working right now so just removing the feature until we fix

### CODE REVIEW

**Comment by plukevdh** [comment]
Wise

**Comment by fromonesrc** [comment]
First commit to Shush was 3 years ago yesterday @plukevdh <3

**Comment by plukevdh** [comment]
wise owl

**Comment by plukevdh** [comment]
What a coincidence.

**Comment by plukevdh** [comment]
Proper props where due:

**Pull request merged**
