### PR TITLE
Turn off other logging

### PR DESCRIPTION
**Pull request by tecnobrat**

### CODE REVIEW

**Comment by plukevdh** [comment]
Security concerns here? What's the motivation for this change?

**Comment by tecnobrat** [comment]
I was trying to figure out why its logging invalid logging messages, this does not fix the bug, I'm still investigating.

**Comment by tecnobrat** [comment]
we are getting log entries that are like:

```
-- { some data }
-- { some data }
-- { some data }{ some data }{ some data }
-- { some data }
```

I have no idea why we see that entry where it starts slapping multiple json strings onto the same line.

**Comment by plukevdh** [comment]
Chances it could be `stdout` vs `stderr`?

**Pull request closed without merging**
